mysite/food/urls.py
from . import views
from django.urls import path


app_name = 'food'
urlpatterns = [
   #/food/
   path('',views.IndexClassView.as_view(),name='index'),
   #/food/1
   path('<int:pk>/',views.FoodDetail.as_view(),name='detail'),
   path('item/',views.item,name='item'),
   # practice
   # path('sri/',views.sri,name='sri'),
   # path('check/',views.meta,name='meta'),

   #add items
   path('add',views.CreateItem.as_view(),name='create_item'),
   #edit
   path('update/<int:id>/',views.update_item,name='update_item'),
   #delete
   path('delete/<int:id>',views.delete_item,name='delete_item'),


]

mysite/mysite/urls.py
from django.contrib import admin
from django.urls import include,path
from users import views as user_views
from django.contrib.auth import views as authentication_views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('food/',include('food.urls')),
    path('register/',user_views.register,name='register'),
    path('login/',authentication_views.LoginView.as_view(template_name='users/login.html'),name='login'),
    path('logout/',authentication_views.LogoutView.as_view(template_name='users/logout.html'),name='logout'),
    path('profile/',user_views.profilepage,name='profile'),
    
]





urlpatterns += [
    # ... the rest of your URLconf goes here ...
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mysite/food/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse

# Create your models here.


class Item(models.Model):

    def __str__(self):
        return self.item_name



    user_name = models.ForeignKey(User,on_delete=models.CASCADE,default=1)
    item_name = models.CharField(max_length=200)
    item_desc = models.CharField(max_length=200)
    item_price = models.IntegerField()
    item_image = models.CharField(max_length=500,default="https://assets.materialup.com/uploads/b03b23aa-aa69-4657-aa5e-fa5fef2c76e8/preview.png")


    def get_absolute_url(self):
            return reverse("food:detail", kwargs={"pk": self.pk})

mysite/users/models.py
# from distutils.command.upload import upload
# from email.policy import default
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class profile(models.Model):
    user = models.OneToOneField(User,on_delete=models.CASCADE)
    image = models.ImageField(default='profilepic.jpg',upload_to='profile_pictures')
    location = models.CharField(max_length=100)

    def __str__(self):
        return self.user.username


       

mysite/food/forms.py
from django import forms
from .models import Item

class ItemForm(forms.ModelForm):
    class Meta:
        model = Item
        fields = ['item_name','item_desc','item_price','item_image']

mysite/users/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm

class RegisterForm(UserCreationForm):
    email = forms.EmailField()


    class Meta:
        model = User
        fields = ['username','email','password1','password2']
        

mysite/food/views.py
from pyexpat import model
from django.shortcuts import render,redirect
from django.http import HttpResponse
from .models import Item
from django.template import loader
from .forms import ItemForm
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView


# Create your views here.
def index(request):
    item_list = Item.objects.all()
    # template = loader.get_template('food/index.html')
    context ={
        'item_list':item_list,

    }
    # this print the extracted database result
    # return HttpResponse(item_list)
    # return HttpResponse(template.render(context,request))
    return render(request,'food/index.html',context)



class IndexClassView(ListView):
    model = Item
    template_name = 'food/index.html'
    context_object_name = 'item_list'





def item(request):
    return HttpResponse('<h1>this is an itme view</h1>')


# from this is a practice 
# def sri(request):
#     return HttpResponse('<h1>heeyyy congo you did that</h1>')

# def meta(request):
#     return HttpResponse('<h2>you are an champion</h2>')



def detail(request,item_id):
    item = Item.objects.get(pk=item_id)
    context ={
        'item':item,
    }
    return render(request,'food/detail.html',context)




class FoodDetail(DetailView):
    model = Item
    template_name = 'food/detail.html'








    
def create_item(request):
    form = ItemForm(request.POST or None)


    if form.is_valid():
        form.save()
        return redirect('food:index')

    return render(request,'food/item-form.html',{'form':form})



class CreateItem(CreateView):
    model = Item
    fields = ['item_name','item_desc','item_price','item_image']
    template_name = 'food/item-form.html'


    def form_valid(self,form):
        form.instance.user_name = self.request.user


        return super().form_valid(form)
        





    

def update_item(request,id):
    item = Item.objects.get(id=id)
    form = ItemForm(request.POST or None, instance=item)

    if form.is_valid():
        form.save()
        return redirect('food:index')

    return render(request,'food/item-form.html',{'form':form,'item':item})


def delete_item(request,id):
    item = Item.objects.get(id=id)

    if request.method == 'POST':
        item.delete()
        return redirect('food:index')


    return render(request,'food/item-delete.html',{'item':item})

mysite/users/views.py
from django.shortcuts import redirect, render
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from .forms import RegisterForm


# Create your views here.

def register(request):
    if request.method == 'POST':
         form = RegisterForm(request.POST)
         if form.is_valid():
            form.save()   
            username = form.cleaned_data.get('username')
            messages.success(request,f'welcome {username}, your account is created')
            return redirect('login')
    else:
        form = RegisterForm()
    return render (request,'users/register.html',{'form':form})


@login_required
def profilepage(request):
    return render(request,'users/profile.html')


    

mysite/food/templates/food/detail.html
{% extends 'food/base.html' %}

{% block body %}
<br><br><br><br><br><br><br>

<div class="container">
    <div class="row">
        <div class="col-md-6">
            <img src="{{ item.item_image }}" class="card" style="height: 300px;">

        </div>

        <div class="col-md-6">
            <h1>{{ object.item_name }}</h1>
            <h2>{{ object.item_desc }}</h2>
            <h3>₹{{ object.item_price }}</h3>
            <h6>Added by <span style="color: #4da6e6;"> {{ item.user_name }} </span></h6><br>
            <a href="{% url 'food:delete_item' item.id %}" class="btn btn-primary">Delete</a>
            <a href="{% url 'food:update_item' item.id %}" class="btn btn-outline-info" style="margin-left: 21px;">Update Item</a><br><br>
            <a href="" class="btn btn-lg btn-success" style="padding: 8px 40px;">Buynow</a>

        </div>

    </div>

</div>







{% endblock %}

mysite/food/templates/food/index.html
{% extends 'food/base.html' %}
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <!-- CSS only -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-0evHe/X+R7YkIZDRvuzKMRqM+OrBnVFBL6DOitfPri4tjfHxaWutUpFmBp4vmVor" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'food/style.css' %}">

    <!-- JavaScript Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-pprn3073KE6tl6bjs2QrFaJGz5/SUsLqktiwsUTF55Jfv3qYSDhgCecCxMW52nD2"
        crossorigin="anonymous"></script>
</head>

<body>


    {% block body %}
    <br><br><br><br><br><br>


    {% for item in item_list %}

    <div class="row">
        <div class="col-md-3 offset-md-2">
            <img class="card img_itm_indx" src="{{ item.item_image }}">
    
        </div>
        <div class="col-md-4">
            <h3>{{ item.item_name }}</h3>
            <h5>{{ item.item_desc }}</h5>
            <h6>₹{{ item.item_price }}</h6>
            <h6>Added by <span style="color: #4da6e6;"> {{ item.user_name }} </span></h6>
            
        </div>
        <div class="col-md-2">
            <a href="{% url 'food:detail' item.id %}" class="btn btn-success">Details</a><br><br><br>
            <a href="{% url 'food:detail' item.id %}" class="btn btn-outline-info">Buynow</a>
            
        </div>

    </div>
    <br>
    <!-- <style>
        .jong:hover
        {
            background-color: #4da6e6;
        }
    </style> -->
    
    
    {% endfor %}



    
    {% endblock %}

    <!-- 
    this is an old code

    


    <ul>
        <li>

          
            <a href="{% url 'food:detail' item.id %}"> {{ item.id }} -- {{ item.item_name }} </a>

        </li>
    </ul>
         -->



    

</body>

</html>

mysite/food/templates/food/item-delete.html
<!-- <form method="POST">
    {% csrf_token %}
    <h2>are you sure you want to delete {{ item.item_name }}</h2>
    <button type="submit">confirm</button>


</form> -->



<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    
<!-- CSS only -->
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-0evHe/X+R7YkIZDRvuzKMRqM+OrBnVFBL6DOitfPri4tjfHxaWutUpFmBp4vmVor" crossorigin="anonymous">

</head>
<body>



    <div class="container">
    
            <center>


                <form method="POST">
                    {% csrf_token %}
                    <h2>are you sure you want to delete <span style="color: #4DA6E5;"> {{ item.item_name }} </span> </h2>
                    <button type="submit" class="btn btn-danger">confirm</button>
    
    
                </form> 
        
            
                <img src="../../../pictures/undraw_Throw_away_re_x60k.png" alt="" style="width: 75%;">

            </center>
              

            

    </div>

    
</body>
</html>

mysite/food/templates/food/item-form.html
{% extends 'food/base.html' %}



{% block body %}

<br><br><br><br><br><br><br>

<div class="container">
    <div class="row">
        <div class="col-md-4 offset-md-2">
            <div class="card">
                <div class="card-header text-white bg-info">
                    <div class="card-title font-weight-bold" style="text-align: center; font-size: 1.2rem;">
                       <h5>Add item</h5> 
                    </div>
                </div>
                <div class="card-body">

                    <form method="POST">
                        {% csrf_token %}
                         {{ form }}
                        <div class="d-grid gap-2 col-6 mx-auto">
                            <button class="btn btn-outline-info" style="margin-top: 25px;" type="submit">Add</button>

                        </div>
                       
                    </form>


                </div>

            </div>
        </div>
        <div class="col-md-4">
            <img src="../../../pictures/undraw_add_friends_re_3xte.png"  alt="">

        </div>

    </div>

</div>


{% endblock %}

mysite/users/templates/users/login.html
{% extends 'food/base.html' %}



{% block body %}

<br><br><br><br><br>
{% if messages %}
{% for message in messages %}
    <div class="alert alert-{{ message.tags }}">
        {{ message }}

    </div>
   

{% endfor %}

{% endif %}
<br><br><br><br>

<div class="container">
    <div class="row">
        <div class="col-md-4 offset-md-4">
            <div class="card">
                <div class="card-header text-white bg-info">
                    <div class="card-title font-weight-bold" style="text-align: center; font-size: 1.2rem;">
                       <h5> Login </h5>
                    </div>
                </div>
                <div class="card-body">
                    <form method="POST">
                        {% csrf_token %}
                        {% for field in form %}
                            <div class="form-group">
                                {{ field.name }}
                                {{ field }}

                            </div>
                        {% endfor %}
                        <div class="d-grid gap-2 col-6 mx-auto">
                            <button class="btn btn-outline-info" style="margin-top: 25px;" type="submit">Login</button>
                        </div>
                  
                    </form>
                </div>

            </div>
        </div>

    </div>

</div>







{% endblock %}

mysite/users/templates/users/logout.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    

    <script src="https://kit.fontawesome.com/f1e02b94da.js" crossorigin="anonymous"></script>
    
    


</head>
<body>
    <center>
        <a href="" style="color: rgb(77,166,230); position: relative; top: 27px; font-weight: 900; font-size: 1.8rem; text-decoration: none;">Healthybud<span style="color: #736FE3; ">d</span>y</a>
        <h1>you have been logged out</h1>
        <i class="fa-regular fa-circle-check fa-5x" style="color: #AADAAB;"></i>
        <h4 style="color: rgb(77,166,230);">thank you</h4>
    </center>

</body>
</html>

mysite/users/templates/users/profile.html
{% extends 'food/base.html' %}



{% block body %}


<br><br><br><br><br><br><br>

<style>
    .card {
      box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2);
      max-width: 700px;
      margin: auto;
      text-align: center;
      font-family: arial;
    }
    
    .title {
      color: grey;
      font-size: 18px;
    }
    
    button {
      border: none;
      outline: 0;
      display: inline-block;
      padding: 8px;
      color: white;
      background-color: #000;
      text-align: center;
      cursor: pointer;
      width: 100%;
      font-size: 18px;
    }
    
    a {
      text-decoration: none;
      font-size: 22px;
      color: black;
    }
    
    button:hover, a:hover {
      opacity: 0.7;
    }
    </style>

<!-- <br><br><br><br><br>
<div class="row">
    <div class="col-md-2 offset-md-4">
        <h1>{{ user.username }}</h1>

    </div>
    <div class="col-md-2">
        <img width="100px" height="100px" src="{{ user.profile.image.url }}">

    </div>
</div> -->






<h2 style="text-align:center">My Profile</h2>

<div class="card">
    <table >
        <tr>
            <td>
                <img style="width: 75%; height: 14%;"  src="{{ user.profile.image.url }}">

            </td>
            <td>
                <h1>{{ user.username }}</h1>
                <h1>{{ user.email }}</h1>

            </td>
        </tr>
    </table>
   
   <a href="">Orders History</a>
   <a href=""> Listing History</a>
   <a href="">Wishlist</a>
   <div style="margin: 24px 0;">
    <a href="#"> <i class="fa-solid fa-store" style="color: #4DA6E6;"></i> </a> 
    <a href="#"> <i class="fa-solid fa-trophy" style="color: #4DA6E6;"></i>  </a>  
    <a href="#"> <i class="fa-solid fa-heart" style="color: #736FE3;"></i> </a>  
    <a href="#"> <i class="fa-solid fa-indian-rupee-sign" style="color: #4DA6E6;"></i> </a> 
  </div>
 
  <a href="http://127.0.0.1:8000/admin/">  <button class="btn btn-primary">Add more details</button> </a>
</div>


{% endblock %}

mysite/users/templates/users/register.html
{% extends 'food/base.html' %}



{% block body %}

<br><br><br><br><br><br>


<div class="container">
    <div class="row">
        <div class="col-md-4 offset-md-2">
            <div class="card">
                <div class="card-header text-white bg-info">
                    <div class="card-title font-weight-bold" style="text-align: center; font-size: 1.2rem;">
                       <h5>Register</h5> 
                    </div>
                </div>
                <div class="card-body">

                    <form method="POST">
                        {% csrf_token %}
                        {% for field in form %}
                            <div class="form-group">
                                {{ field.name }}
                                <br>
                                {{ field }}
                            </div>
                        {% endfor %}
                        <div class="d-grid gap-2 col-6 mx-auto">
                            <button class="btn btn-outline-info" style="margin-top: 25px;" type="submit">Signup</button>

                        </div>
                       
                    </form>


                </div>

            </div>
        </div>
        <div class="col-md-4">
            <img src="../../../pictures/undraw_Editable_re_4l94.png" alt=""> 

        </div>

    </div>

</div>



{% endblock %}